server:
  port: 8080
  servlet:
    context-path: /managePhoneNumbers

management:
    endpoint:
      shutdown:
        enabled: true
    endpoints:
      web:
        exposure:
          include: shutdown, health, info
